# Site settings
title: "Riyaz Ali"
description: > 
  My tinkering and findings with code and tech

author: Riyaz Ali
email: me@riyazali.net
twitter_username: riyaz2302
github_username: riyaz-ali

#baseurl: # the subpath of your site, e.g. /blog
url: "https://riyazali.net" # the base hostname & protocol for your site

google_analytics_id:
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:title.html

sass:
  style: compressed

exclude: [vendor]

